[package]
name = "id-pool"
version = "0.1.0"
authors = ["adamsky <adamsky@enum.space>"]
edition = "2018"

[features]
default = ["usize"]
usize = []
u64 = []
u32 = []
u16 = []

[dependencies]
serde = { version = "1.0.114", optional = true }